In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings = pd.read_csv("../ml-25m/ratings.csv")

print(ratings.shape)

ratings.head()

(25000095, 4)

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [3]:
ratings = ratings.sample(
    n=500000,
    random_state=42
).reset_index(drop=True)

print(ratings.shape)

(500000, 4)

In [4]:
user_features = ratings.groupby("userId").agg(
    avg_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()

user_features.head()

   userId  avg_rating  rating_count
0       1    3.500000             1
1       2    4.000000             2
2       3    3.690476            21
3       4    3.600000             5
4       5    3.000000             1

In [5]:
movie_features = ratings.groupby("movieId").agg(
    avg_movie_rating=("rating", "mean"),
    movie_rating_count=("rating", "count")
).reset_index()

movie_features.head()

   movieId  avg_movie_rating  movie_rating_count
0        1          3.858120                1170
1        2          3.281000                 500
2        3          3.170886                 237
3        4          2.766667                  45
4        5          3.113636                 220

In [6]:
data = ratings.merge(
    user_features,
    on="userId"
)

data.head()

   userId  movieId  rating   timestamp  avg_rating  rating_count
0   99476   104374     3.5  1467897440    3.583333             6
1  107979     2634     4.0   994007728    3.937500            16
2  155372     1614     3.0  1097887531    2.863636            11
3   65225     7153     4.0  1201382275    4.000000             2
4   79161      500     5.0  1488915363    4.076923            13

In [7]:
data = data.merge(
    movie_features,
    on="movieId"
)

data.head()

,userId,movieId,rating,timestamp,avg_rating,rating_count,avg_movie_rating,movie_rating_count
0,99476,104374,3.5,1467897440,3.583333,6,4.048387,93
1,107979,2634,4.0,994007728,3.937500,16,3.111111,18
2,155372,1614,3.0,1097887531,2.863636,11,3.269608,102
3,65225,7153,4.0,1201382275,4.000000,2,4.142063,989
4,79161,500,5.0,1488915363,4.076923,13,3.451994,677

In [8]:
print(data.columns)

Index(['userId', 'movieId', 'rating', 'timestamp', 'avg_rating',
       'rating_count', 'avg_movie_rating', 'movie_rating_count'],
      dtype='str')

In [9]:
data.to_csv("../ctr_features.csv", index=False)

print("CTR features saved successfully!")

CTR features saved successfully!